providers = ["go", "node"]

[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["cd blobkeyhelper && go mod download && go build -o ../bin/blobkeyhelper ./cmd/blobkeyhelper && cd .. && npm ci && npm run build"]
