providers = ["go", "node"]

[phases.setup]
nixPkgs = ["go", "nodejs"]

[phases.build]
cmds = ["cd blobkeyhelper && go mod download && go build -o ../bin/blobkeyhelper . && cd .. && npm ci && npm run build"]
